// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwgV7ALLv4s7WK4Y602EykSzI9ePkaC7A',
    appId: '1:751119156672:web:ef1dd24e3a42d38ac87425',
    messagingSenderId: '751119156672',
    projectId: 'flutter-todo-lab-33e2d',
    authDomain: 'flutter-todo-lab-33e2d.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-33e2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNrMg4SgflPLVb1di873Ffa752vmFfU6I',
    appId: '1:751119156672:android:8aaf886e15deac38c87425',
    messagingSenderId: '751119156672',
    projectId: 'flutter-todo-lab-33e2d',
    storageBucket: 'flutter-todo-lab-33e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3g4UfXj1HFww1ojG8eklfXM0X1X5HwBE',
    appId: '1:751119156672:ios:09c9e323e10f08f0c87425',
    messagingSenderId: '751119156672',
    projectId: 'flutter-todo-lab-33e2d',
    storageBucket: 'flutter-todo-lab-33e2d.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3g4UfXj1HFww1ojG8eklfXM0X1X5HwBE',
    appId: '1:751119156672:ios:09c9e323e10f08f0c87425',
    messagingSenderId: '751119156672',
    projectId: 'flutter-todo-lab-33e2d',
    storageBucket: 'flutter-todo-lab-33e2d.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwgV7ALLv4s7WK4Y602EykSzI9ePkaC7A',
    appId: '1:751119156672:web:f1d811d74e5c39b7c87425',
    messagingSenderId: '751119156672',
    projectId: 'flutter-todo-lab-33e2d',
    authDomain: 'flutter-todo-lab-33e2d.firebaseapp.com',
    storageBucket: 'flutter-todo-lab-33e2d.appspot.com',
  );
}
